### ISSUE TITLE
missing images and broken link

### ISSUE THREAD

**Issue by MoienTajik** [stakater/developer-handbook#40]
There's an issue in [Object Calisthenics](https://github.com/stakater/developer-handbook/blob/master/architecture/object-calisthenics.md) article.

This repository is no longer exist which is mentioned in the [References section](https://github.com/stakater/developer-handbook/blob/master/architecture/object-calisthenics.md#references): https://github.com/TheLadders/object-calisthenics

Also, in [this](https://github.com/stakater/developer-handbook/blob/master/architecture/object-calisthenics.md#8-do-not-use-classes-with-more-than-two-instance-variables) section, an image which refers to that repository is used and it's broken too. 
The URL of the broken image is:
https://raw.githubusercontent.com/TheLadders/object-calisthenics/master/assets/2-instance-variables.png

**Comment by ahmedwaleedmalik** [comment]
Fixed with #52 https://github.com/stakater/developer-handbook/pull/52
